services:
  app_proxy:
    image: nginx:alpine
    restart: always
    environment:
      APP_HOST: litecoin_node_dashboard
      APP_PORT: 80

  litecoin_node_dashboard:
    image: nginx:alpine
    container_name: litecoin_node_dashboard
    restart: always
